### ISSUE TITLE
Prepare public release

### ISSUE THREAD

**Issue by mdziekon** [mdziekon/octoprint-spoolman#4]
# Description

Prepare for public release.

# TODO

- [ ] Update all necessary plugin properties
- [ ] Make repo public
- [ ] Create PR in github.com/OctoPrint/plugins.octoprint.org/
